const INPUT_ALPHA_SET_FOCUS = 'INPUT_ALPHA_SET_FOCUS'
const SET_POPUP_UIFORM_ALPHA_OPEN = 'SET_POPUP_UIFORM_ALPHA_OPEN'
const SET_POPUP_UIFORM_ALPHA_CLOSE = 'SET_POPUP_UIFORM_ALPHA_CLOSE'
const SET_POPUP_UIFORM_ALPHA_TOGGLE = 'SET_POPUP_UIFORM_ALPHA_TOGGLE'

export {
  INPUT_ALPHA_SET_FOCUS,
  SET_POPUP_UIFORM_ALPHA_OPEN,
  SET_POPUP_UIFORM_ALPHA_CLOSE,
  SET_POPUP_UIFORM_ALPHA_TOGGLE
}
