const POPUP_ALPHA_OPEN = 'POPUP_ALPHA_OPEN'
const POPUP_ALPHA_CLOSE = 'POPUP_ALPHA_CLOSE'
const POPUP_ALPHA_TOGGLE = 'POPUP_ALPHA_TOGGLE'

export { POPUP_ALPHA_OPEN, POPUP_ALPHA_CLOSE, POPUP_ALPHA_TOGGLE }
