const INPUT_ALPHA_SET_FOCUS = 'INPUT_ALPHA_SET_FOCUS'
const POPUP_ALPHA_OPEN = 'POPUP_ALPHA_OPEN'
const POPUP_ALPHA_CLOSE = 'POPUP_ALPHA_CLOSE'
const POPUP_ALPHA_TOGGLE = 'POPUP_ALPHA_TOGGLE'

export {
  INPUT_ALPHA_SET_FOCUS,
  POPUP_ALPHA_OPEN,
  POPUP_ALPHA_CLOSE,
  POPUP_ALPHA_TOGGLE
}
